apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-status-api
  namespace: trapp-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-status-api
  template:
    metadata:
      labels:
        app: edge-status-api
    spec:
      containers:
        - name: edge-status-api
          image: ghcr.io/victor-trapp/edge-status-api:0.1.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              value: "0.1.0"
          envFrom:
            - configMapRef:
                name: edge-status-config
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi